[theme]
primaryColor = "#2E5090"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "minimal"

[ui]
hideTopBar = false
# Cache buster - jueves,  6 de noviembre de 2025, 11:43:47 -0300
